### ISSUE TITLE
Can we remove the specific version of the library?

### ISSUE THREAD

**Issue by Panchorn** [okgolove/robotframework-jenkins#11]
[setup.py](https://github.com/okgolove/robotframework-jenkins/blob/master/setup.py)
`REQUIREMENTS = [
    'python-jenkins==0.4.15',
    'robotframework==3.0.2',
    'requests==2.18.4'
]`

can we change to
`REQUIREMENTS = [
    'python-jenkins',
    'robotframework',
    'requests'
]`

**Comment by okgolove** [comment]
Hi @Panchorn!
Thank you for the issue.

I'm pretty sure we can and we should change this.
It must be at least >= not ==.

What is your point?
