### ISSUE TITLE
create new jobs with copy config from existing job

### ISSUE THREAD

**Issue by davesliu** [okgolove/robotframework-jenkins#17]
Hello

I want to create new jobs by copying them from existing job
and need to change some params in the config.xml for the newly created jobs.
Is there anyway that I can do with robotframework-jenkins?

Thanks.

**Comment by okgolove** [comment]
@davesliu hi! Thank you for raising an issue.

Currently there is no option to copy existing job. Feel free to create a PR.
I will try to take a look.

**Comment by okgolove** [comment]
Hi @davesliu! Have you resolved the issue?
I've just realised you can use [Get Jenkins Job Xml keyword](https://okgolove.github.io/robotframework-jenkins/#Get%20Jenkins%20Job%20Xml) and change anything in the XML.
Then, create a job using [Create Jenkins Job keyword](https://okgolove.github.io/robotframework-jenkins/#Create%20Jenkins%20Job)
